name: Update YouTube Videos

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with YouTube videos
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: "UCY0EqBS4AzvMnAdXJ3VcODw"
          api_key: ${{ secrets.YOUTUBE_API_KEY }}
          max_videos: 6  # Adjust the number of videos to display
          output_file: "README.md"  # Update README file
          format: "markdown"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated YouTube videos" || exit 0
          git push
